[2025-06-19T21:06:00.101+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-19T21:06:00.131+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: beer_bronze_dag.fetch_beer_data manual__2025-06-19T21:00:50.614531+00:00 [queued]>
[2025-06-19T21:06:00.139+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: beer_bronze_dag.fetch_beer_data manual__2025-06-19T21:00:50.614531+00:00 [queued]>
[2025-06-19T21:06:00.140+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-19T21:06:00.153+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_beer_data> on 2025-06-19 21:00:50.614531+00:00
[2025-06-19T21:06:00.157+0000] {standard_task_runner.py:63} INFO - Started process 88 to run task
[2025-06-19T21:06:00.161+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'beer_bronze_dag', 'fetch_beer_data', 'manual__2025-06-19T21:00:50.614531+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/beer_dag.py', '--cfg-path', '/tmp/tmpem26ivao']
[2025-06-19T21:06:00.163+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask fetch_beer_data
[2025-06-19T21:06:00.181+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-19T21:06:00.238+0000] {task_command.py:426} INFO - Running <TaskInstance: beer_bronze_dag.fetch_beer_data manual__2025-06-19T21:00:50.614531+00:00 [running]> on host 32e0ab00ce3c
[2025-06-19T21:06:00.353+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='lucascarvalho' AIRFLOW_CTX_DAG_ID='beer_bronze_dag' AIRFLOW_CTX_TASK_ID='fetch_beer_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T21:00:50.614531+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T21:00:50.614531+00:00'
[2025-06-19T21:06:00.355+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-19T21:06:01.017+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-19T21:06:01.018+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/beer_dag.py", line 12, in fetch_beer_data
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2025-06-19T21:06:01.037+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=beer_bronze_dag, task_id=fetch_beer_data, run_id=manual__2025-06-19T21:00:50.614531+00:00, execution_date=20250619T210050, start_date=20250619T210600, end_date=20250619T210601
[2025-06-19T21:06:01.060+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task fetch_beer_data (Expecting value: line 1 column 1 (char 0); 88)
[2025-06-19T21:06:01.099+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-19T21:06:01.122+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T21:06:01.124+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
